<?php
return array(
  'escolaridad'=>[
    ''=>'-- Seleccione --',
    '0'=>'PRIMARIA',
    '1'=>'SECUNDARIA',
    '2'=>'BACHILLERATO',
    '3'=>'LICENCIATURA',
    '4'=>'MAESTRIA',
    '5'=>'DOCTORADO',
    '6'=>'OTRO'
    ],
    'estadocivil'=>[
      '0'=>'SOLTERO',
      '1'=>'CASADO'
    ],
    'pagos'=>[
      '0'=>'DEPOSITO BANCARIO',
      '1'=>'CHEQUE'
      ],
    'meses'=>array(
        "",
        "Enero",
        "Febrero",
        "Marzo",
        "Abril",
        "Mayo",
        "Junio",
        "Julio",
        "Agosto",
        "Septiembre",
        "Octubre",
        "Noviembre",
        "Diciembre"
      ),
      'catalogos'=>array(
        "adscripciones",
        "plazas",
        "tabulador",
        "horarios"
      )
  );
  ?>
